name: LTD
on: 
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: 'npm'
      - name: get code
        uses: actions/checkout@v3
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Lint
        run: npm run lint

  Test:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: 'npm'
      - name: get code
        uses: actions/checkout@v3
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Test Code
        run: npm run test

  Build:
    # needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: 'npm'
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
      
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Get build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
    - name: output content
      run: ls -ltr
    - name: Deploy
      run: echo "Deploying........."
