name: LTD
on: 
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Lint
        run: npm run lint

  Test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Test Code
        run: npm run test

  Build:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install Dependency
        run: npm ci
      - name: Build Code
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dis-files
          path: |
            dist
            package.json
      
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      run: echo "Deploying........."
